spring.config.import=optional:file:.env[.properties]
spring.application.name=vaultaPass
spring.datasource.url=jdbc:postgresql://localhost:5432/vaultapass
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}