spring.config.import=optional:file:.env[.properties]
spring.application.name=vaulta
spring.datasource.url=jdbc:postgresql://localhost:5432/vaulta
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
